TASK: oad
DDP:
  ENABLE: True
  MASTER_ADDR: localhost
  MASTER_PORT: 12356
  SHARD_ID: 0
  NUM_SHARDS: 1
DATA:
  DATA_INFO: data/annotations/data_info.json
  DATA_NAME: "THUMOS"
  DATA_ROOT: None
  CLASS_NAMES: None
  NUM_CLASSES: None
  IGNORE_INDEX: None
  METRICS: None
  FPS: None
  TRAIN_SESSION_SET: None
  TEST_SESSION_SET: None

INPUT:
  MODALITY: "visual"
  VISUAL_FEATURE: "rgb_npy"
  MOTION_FEATURE: "flow_kinetics_bninception"
  TARGET_PERFRAME: target_perframe
  DIV_255: True
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  KEEP_ASPECT: True
  DO_RESIZE_CROP: True
  TRAIN:
    FLIP_P: 0.5 # probability to do the horizontal flip to the inputs.
    RESIZE_SCALE: [256, 320]
    CROP_SIZE: [224, 224]
    STRIDE: -1
  TEST:
    RESIZE_SCALE: [256]
    CROP_SIZE: [224, 224]
    STRIDE: -1

DATA_LOADER:
  PIN_MEMORY: False
  NUM_WORKERS: 6
  BATCH_SIZE: 16
  TRAIN_BATCH_SIZE: 16
  TEST_BATCH_SIZE: 16

MODEL:
  MODEL_NAME: "E2E_LSTR"
  CHECKPOINT: ""
  SPATIAL:
    NAME: rgb_kinetics_resnet50
    FREEZE_BN: True
    FREEZE_ALL: False
  FEATURE_HEAD:
    LINEAR_ENABLED: True
    LINEAR_OUT_FEATURES: 1024
  LSTR:
    NUM_HEADS: 16
    DIM_FEEDFORWARD: 1024
    DROPOUT: 0.2
    MEMORY_SAMPLE_RATE: 4
    AGES_MEMORY_SECONDS: 0
    LONG_MEMORY_SECONDS: 128
    LONG_MODULE: [[16, 1, True], [32, 2, True]]
    WORK_MODULE: [32, 2, True]
  CRITERIONS: [["MCE", {}]]

PARTIAL_FEEDBACK: # the same meaning as Stochastic Backpropagation.
  ENABLE: True
  INFERENCE_SPLIT: True
  SPLIT_SIZE: 128
  SAMPLE_METHOD: predefined # predefined
  SAMPLE_STRATEGY: uniform_center
  SAMPLE_JITTER: True # only valid when SAMPLE_STRATEGY is uniform_center
  SAMPLE_RATE: 0.2

SOLVER:
  PHASES: ["train"]
  NUM_EPOCHS: 25
  START_EPOCH: 1
  SPATIAL:
    OPTIMIZER: adam
    BASE_LR: 3e-6
    WEIGHT_DECAY: 5e-5
    SCHEDULER:
      NAME: warmup_multistep
      MILESTONES: [13, 24]
      WARMUP_EPOCHS: 1
      WARMUP_FACTOR: 0.1
      WARMUP_METHOD: linear # linear, constant
      GAMMA: 0.1
  TEMPORAL:
    OPTIMIZER: adam
    BASE_LR: 5e-5
    WEIGHT_DECAY: 5e-5
    SCHEDULER:
      NAME: multistep
      MILESTONES: [13, 24]
      GAMMA: 0.1

TENSORBOARD:
  ENABLE: True

SEED: 0
OUTPUT_DIR: checkpoints/thumos-lstr
